# Imports

In [1]:
import pandas as pd

# Transformations
For the model we need an specific format.

In [2]:
archivos = ['../features/2015.csv', '../features/2016.csv', '../features/2017.csv', '../features/2018.csv', '../features/2019.csv']
dataframes = []

for archivo in archivos:
    df = pd.read_csv(archivo)
    df['Year'] = archivo.split('/')[-1].split('.')[0]
    dataframes.append(df)

combined_df = pd.concat(dataframes, ignore_index=True)
combined_df.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),...,Trust..Government.Corruption.,Dystopia.Residual,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Perceptions of corruption
0,Switzerland,Western Europe,1.0,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Iceland,Western Europe,2.0,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Denmark,Western Europe,3.0,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Norway,Western Europe,4.0,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Canada,North America,5.0,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
print(combined_df.columns)

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual', 'Year', 'Lower Confidence Interval',
       'Upper Confidence Interval', 'Happiness.Rank', 'Happiness.Score',
       'Whisker.high', 'Whisker.low', 'Economy..GDP.per.Capita.',
       'Health..Life.Expectancy.', 'Trust..Government.Corruption.',
       'Dystopia.Residual', 'Overall rank', 'Country or region', 'Score',
       'GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Perceptions of corruption'],
      dtype='object')

In [4]:
def unir_valores(series):
    valores_no_nulos = series.dropna().unique()
    if len(valores_no_nulos) == 1:
        return valores_no_nulos[0] 
    return ', '.join(map(str, valores_no_nulos))

combined_df['country'] = combined_df[['Country', 'Country or region']].agg(unir_valores, axis=1)
combined_df['happiness_rank'] = combined_df[['Happiness Rank', 'Happiness.Rank', 'Overall rank']].agg(unir_valores, axis=1)
combined_df['happiness_score'] = combined_df[['Happiness Score', 'Happiness.Score', 'Score']].agg(unir_valores, axis=1)
combined_df['GDP'] = combined_df[['Economy (GDP per Capita)', 'Economy..GDP.per.Capita.', 'GDP per capita']].agg(unir_valores, axis=1)
combined_df['life_expectancy'] = combined_df[['Health (Life Expectancy)', 'Health..Life.Expectancy.', 'Healthy life expectancy']].agg(unir_valores, axis=1)
combined_df['freedom'] = combined_df[['Freedom', 'Freedom to make life choices']].agg(unir_valores, axis=1)
combined_df['generosity'] = combined_df[['Generosity']].agg(unir_valores, axis=1)
combined_df['government_corruption'] = combined_df[['Trust (Government Corruption)', 'Trust..Government.Corruption.', 'Perceptions of corruption']].agg(unir_valores, axis=1)
combined_df['dystopia_residual'] = combined_df[['Dystopia Residual', 'Dystopia.Residual']].agg(unir_valores, axis=1)
combined_df['family'] = combined_df[['Family', 'Social support']].agg(unir_valores, axis=1)

columns_to_drop = ['Country or region', 'Happiness.Rank', 'Overall rank', 'Happiness.Score', 'Score',
                   'Economy (GDP per Capita)', 'Economy..GDP.per.Capita.', 'GDP per capita',
                   'Health (Life Expectancy)', 'Health..Life.Expectancy.', 'Healthy life expectancy',
                   'Freedom to make life choices', 'Trust (Government Corruption)', 'Trust..Government.Corruption.',
                   'Perceptions of corruption', 'Dystopia.Residual', 'Social support']

combined_df.drop(columns=columns_to_drop, inplace=True)

combined_df.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Family,Freedom,Generosity,Dystopia Residual,Year,...,country,happiness_rank,happiness_score,GDP,life_expectancy,freedom,generosity,government_corruption,dystopia_residual,family
0,Switzerland,Western Europe,1.0,7.587,0.03411,1.34951,0.66557,0.29678,2.51738,2015,...,Switzerland,1.0,7.587,1.39651,0.94143,0.66557,0.29678,0.41978,2.51738,1.34951
1,Iceland,Western Europe,2.0,7.561,0.04884,1.40223,0.62877,0.43630,2.70201,2015,...,Iceland,2.0,7.561,1.30232,0.94784,0.62877,0.43630,0.14145,2.70201,1.40223
2,Denmark,Western Europe,3.0,7.527,0.03328,1.36058,0.64938,0.34139,2.49204,2015,...,Denmark,3.0,7.527,1.32548,0.87464,0.64938,0.34139,0.48357,2.49204,1.36058
3,Norway,Western Europe,4.0,7.522,0.03880,1.33095,0.66973,0.34699,2.46531,2015,...,Norway,4.0,7.522,1.45900,0.88521,0.66973,0.34699,0.36503,2.46531,1.33095
4,Canada,North America,5.0,7.427,0.03553,1.32261,0.63297,0.45811,2.45176,2015,...,Canada,5.0,7.427,1.32629,0.90563,0.63297,0.45811,0.32957,2.45176,1.32261

In [5]:
combined_df.describe()

,Happiness Rank,Happiness Score,Standard Error,Family,Freedom,Generosity,Dystopia Residual,Lower Confidence Interval,Upper Confidence Interval,Whisker.high,Whisker.low,happiness_rank,happiness_score,GDP,life_expectancy,freedom,generosity,family
count,315.000000,315.000000,158.000000,470.000000,470.000000,782.000000,315.000000,157.000000,157.000000,155.000000,155.000000,782.000000,782.000000,782.000000,782.000000,782.000000,782.000000,782.000000
mean,79.238095,5.378949,0.047885,0.990347,0.402828,0.218576,2.212032,5.282395,5.481975,5.452326,5.255713,78.698210,5.379018,0.916047,0.612416,0.411091,0.218576,1.078392
std,45.538922,1.141531,0.017146,0.318707,0.150356,0.122321,0.558728,1.148043,1.136493,1.118542,1.145030,45.182384,1.127456,0.407340,0.248309,0.152880,0.122321,0.329548
min,1.000000,2.839000,0.018480,0.000000,0.000000,0.000000,0.328580,2.732000,3.078000,2.864884,2.521116,1.000000,2.693000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,40.000000,4.510000,0.037268,0.793000,0.297615,0.130000,1.884135,4.327000,4.465000,4.608172,4.374955,40.000000,4.509750,0.606500,0.440183,0.309768,0.130000,0.869363
50%,79.000000,5.286000,0.043940,1.025665,0.418347,0.201982,2.211260,5.237000,5.419000,5.370032,5.193152,79.000000,5.322000,0.982205,0.647310,0.431000,0.201982,1.124735
75%,118.500000,6.269000,0.052300,1.228745,0.516850,0.278832,2.563470,6.154000,6.434000,6.194600,6.006527,118.000000,6.189500,1.236187,0.808000,0.531000,0.278832,1.327250
max,158.000000,7.587000,0.136930,1.610574,0.669730,0.838075,3.837720,7.460000,7.669000,7.622030,7.479556,158.000000,7.769000,2.096000,1.141000,0.724000,0.838075,1.644000

In [6]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 782 entries, 0 to 781
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Country                    470 non-null    object
 1   Region                     315 non-null    object
 2   Happiness Rank             315 non-null    float64
 3   Happiness Score            315 non-null    float64
 4   Standard Error             158 non-null    float64
 5   Family                     470 non-null    float64
 6   Freedom                    470 non-null    float64
 7   Generosity                 782 non-null    float64
 8   Dystopia Residual          315 non-null    float64
 9   Year                       782 non-null    object
 10  Lower Confidence Interval  157 non-null    float64
 11  Upper Confidence Interval  157 non-null    float64
 12  Whisker.high               155 non-null    float64
 13  Whisker.low                155 non-null    float64
 14  country                    782 non-null    object
 15  happiness_rank             782 non-null    float64
 16  happiness_score            782 non-null    float64
 17  GDP                        782 non-null    float64
 18  life_expectancy            782 non-null    float64
 19  freedom                    782 non-null    float64
 20  generosity                 782 non-null    float64
 21  government_corruption      782 non-null    object
 22  dystopia_residual          782 non-null    object
 23  family                     782 non-null    float64
dtypes: float64(18), object(6)
memory usage: 146.8+ KB

In [7]:
combined_df.to_csv('../features/combined_happiness_data.csv', index=False)

In [13]:
df2015 = pd.read_csv('../features/2015.csv')
df2016 = pd.read_csv('../features/2016.csv')
df2017 = pd.read_csv('../features/2017.csv')
df2018 = pd.read_csv('../features/2018.csv')
df2019 = pd.read_csv('../features/2019.csv')

df2015.info()
df2016.info()
df2017.info()
df2018.info()
df2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Region                         158 non-null    object
 2   Happiness Rank                 158 non-null    int64
 3   Happiness Score                158 non-null    float64
 4   Standard Error                 158 non-null    float64
 5   Economy (GDP per Capita)       158 non-null    float64
 6   Family                         158 non-null    float64
 7   Health (Life Expectancy)       158 non-null    float64
 8   Freedom                        158 non-null    float64
 9   Trust (Government Corruption)  158 non-null    float64
 10  Generosity                     158 non-null    float64
 11  Dystopia Residual              158 non-null    float64
dtypes: float64(9), int64(1), object(2)
memory usage: 14.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        157 non-null    object
 1   Region                         157 non-null    object
 2   Happiness Rank                 157 non-null    int64
 3   Happiness Score                157 non-null    float64
 4   Lower Confidence Interval      157 non-null    float64
 5   Upper Confidence Interval      157 non-null    float64
 6   Economy (GDP per Capita)       157 non-null    float64
 7   Family                         157 non-null    float64
 8   Health (Life Expectancy)       157 non-null    float64
 9   Freedom                        157 non-null    float64
 10  Trust (Government Corruption)  157 non-null    float64
 11  Generosity                     157 non-null    float64
 12  Dystopia Residual              157 non-null    float64
dtypes: float64(10), int64(1), object(2)
memory usage: 16.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        155 non-null    object
 1   Happiness.Rank                 155 non-null    int64
 2   Happiness.Score                155 non-null    float64
 3   Whisker.high                   155 non-null    float64
 4   Whisker.low                    155 non-null    float64
 5   Economy..GDP.per.Capita.       155 non-null    float64
 6   Family                         155 non-null    float64
 7   Health..Life.Expectancy.       155 non-null    float64
 8   Freedom                        155 non-null    float64
 9   Generosity                     155 non-null    float64
 10  Trust..Government.Corruption.  155 non-null    float64
 11  Dystopia.Residual              155 non-null    float64
dtypes: float64(10), int64(1), object(1)
memory usage: 14.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Score                         156 non-null    float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy life expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Perceptions of corruption     155 non-null    float64
dtypes: float64(7), int64(1), object(1)
memory usage: 11.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Score                         156 non-null    float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy life expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Perceptions of corruption     156 non-null    float64
dtypes: float64(7), int64(1), object(1)
memory usage: 11.1+ KB